// Generates desktop/renderer/index.html from app/index.html.
//
// The two shells are the same page: same markup, same stylesheet, same
// modules. They differ only in how the Electron renderer reaches files one
// directory deeper, and in the quality flag core/quality.js reads before
// anything else runs. Keeping the desktop copy by hand meant every change to
// the app's markup was two edits and one chance to forget the second — this
// makes forgetting impossible instead of merely unlikely.
//
//   node tools/build_desktop_shell.js          write the file
//   node tools/build_desktop_shell.js --check  fail if it is out of date
//
// Run it after touching app/index.html. --check is what CI would call.

const { readFileSync, writeFileSync } = require("node:fs");
const { join } = require("node:path");

const root = join(__dirname, "..");
const SOURCE = join(root, "app", "index.html");
const TARGET = join(root, "desktop", "renderer", "index.html");

// Each rule is [description, find, replace]. They are applied in order and
// every one must match exactly once — a rule that stops matching means the
// source markup moved and this script would otherwise silently emit a broken
// desktop shell.
const RULES = [
  [
    "head: desktop title, stylesheet path, quality flag",
    /  <title data-i18n="app\.title">[^<]*<\/title>\n(?:  <meta name="description"[\s\S]*?\/>\n)?  <link rel="icon"[^\n]*\n  <link rel="stylesheet" href="style\.css" \/>\n  <link rel="modulepreload"[^\n]*\n/,
    `  <title>AimonSite Desktop</title>
  <!-- Same stylesheet as the web build — one design system, no duplication. -->
  <link rel="stylesheet" href="../../app/style.css" />
  <script>
    // Read by core/quality.js before anything else runs. Must be set
    // before core/main.js is imported below.
    window.__AIMONSITE_QUALITY__ = "desktop";
  </script>
`,
  ],
  ["importmap: three", '"three": "../vendor/', '"three": "../../vendor/'],
  ["importmap: three/addons", '"three/addons/": "../vendor/', '"three/addons/": "../../vendor/'],
  // There is no landing page in the desktop build, so the brand link has
  // nowhere to go — it stays as a header rather than a dead link out.
  ["sidebar brand link", '<a id="home-back" class="sidebar-brand" href="../"', '<a id="home-back" class="sidebar-brand" href=""'],
  ["entry module", '<script type="module" src="../core/main.js"></script>', '<script type="module" src="../../core/main.js"></script>'],
];

const BANNER = "<!-- Generated by tools/build_desktop_shell.js from app/index.html. Do not edit. -->\n";

// git checks these files out with CRLF on Windows and LF elsewhere, so every
// rule below is written against LF and the file's own ending is put back on
// the way out. Without this the rules match on one platform and silently
// match nothing on the other.
const readNormalized = (path) => readFileSync(path, "utf8").replace(/\r\n/g, "\n");

function build() {
  let html = readNormalized(SOURCE);

  for (const [description, find, replace] of RULES) {
    const before = html;
    if (typeof find === "string") {
      if (before.split(find).length !== 2) {
        throw new Error(`build_desktop_shell: rule "${description}" matched ${before.split(find).length - 1} times, expected exactly 1`);
      }
      html = before.replace(find, replace);
    } else {
      const matches = before.match(new RegExp(find.source, find.flags + "g"));
      if (!matches || matches.length !== 1) {
        throw new Error(`build_desktop_shell: rule "${description}" matched ${matches?.length ?? 0} times, expected exactly 1`);
      }
      html = before.replace(find, replace);
    }
  }

  return html.replace("<!doctype html>\n", `<!doctype html>\n${BANNER}`);
}

const expected = build();
const check = process.argv.includes("--check");

if (check) {
  let actual = "";
  try {
    actual = readNormalized(TARGET);
  } catch {
    // Missing target is just the strongest form of out of date.
  }
  if (actual !== expected) {
    console.error("desktop/renderer/index.html is out of date — run: node tools/build_desktop_shell.js");
    process.exit(1);
  }
  console.log("desktop/renderer/index.html is up to date.");
} else {
  const eol = readFileSync(SOURCE, "utf8").includes("\r\n") ? "\r\n" : "\n";
  writeFileSync(TARGET, eol === "\n" ? expected : expected.replace(/\n/g, eol));
  console.log(`Wrote ${TARGET}`);
}
